# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
name: Build and deploy Node.js app to Azure Web App - traveltdea

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install, build & test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact
        run: zip -r release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Save publish profile
        run: |
          mkdir -p kudu
          echo "${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}" > kudu/profile.publishsettings

      - name: Extract app name & resource group
        id: app-info
        run: |
          APP_NAME=$(xmllint --xpath 'string(//publishProfile[@publishMethod="MSDeploy"]/@siteName)' kudu/profile.publishsettings)
          echo "app_name=$APP_NAME" >> "$GITHUB_OUTPUT"
          echo "resource_group=${{ secrets.AZURE_RESOURCE_GROUP }}" >> "$GITHUB_OUTPUT"

      - name: Azure CLI login
        uses: azure/login@v2
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      - name: Stop Web App
        run: |
          az webapp stop \
            --name ${{ steps.app-info.outputs.app_name }} \
            --resource-group ${{ steps.app-info.outputs.resource_group }}

      - name: Remove run-from-package (OneDeploy) setting
        run: |
          az webapp config appsettings delete \
            --name ${{ steps.app-info.outputs.app_name }} \
            --resource-group ${{ steps.app-info.outputs.resource_group }} \
            --setting-names WEBSITE_RUN_FROM_PACKAGE
        # Elimina el setting que monta el ZIP en modo solo-lectura y dispara OneDeploy :contentReference[oaicite:2]{index=2}

      - name: Wait for app to stop
        run: sleep 10

      - name: ZIP Deploy via Azure CLI
        run: |
          az webapp deploy \
            --resource-group ${{ steps.app-info.outputs.resource_group }} \
            --name ${{ steps.app-info.outputs.app_name }} \
            --type zip \
            --src-path release.zip
        # Usa Kudu ZipDeploy para reemplazar contenido sin conflictos :contentReference[oaicite:3]{index=3}

      - name: Start Web App
        run: |
          az webapp start \
            --name ${{ steps.app-info.outputs.app_name }} \
            --resource-group ${{ steps.app-info.outputs.resource_group }}

