# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
name: Build and deploy Node.js app to Azure Web App - travelstdea

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip ./* -x "node_modules/*" "*.git*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Remove zip file
        run: rm release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C289269F97494C6EA9E99490992A3961 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_96222BBB683243C8BD72D8DC5CA4144F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8BC739B6E0A145C28631C86FED07216A }}

      - name: Clean previous deployment lock (if exists)
        run: |
          echo "Revisando si hay un despliegue en progreso..."
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST "https://travelstdea.scm.azurewebsites.net/api/deployments/latest?deployer=GITHUB ACTIONS" \
            -u ${{ secrets.AZURE_DEPLOY_USERNAME }}:${{ secrets.AZURE_DEPLOY_PASSWORD }})
          if [ "$RESPONSE" == "409" ]; then
            echo "Hay un despliegue en progreso. Intentando cancelar..."
            curl -X DELETE "https://travelstdea.scm.azurewebsites.net/api/deployments/latest" \
              -u ${{ secrets.AZURE_DEPLOY_USERNAME }}:${{ secrets.AZURE_DEPLOY_PASSWORD }}
            echo "Cancelación enviada. Esperando 10 segundos antes de continuar..."
            sleep 10
          fi

      - name: Retry deploy to Azure Web App up to 3 times
        run: |
          for i in 1 2 3; do
            echo "Intento $i de despliegue..."
            npx azure-webapps-deploy --app-name 'travelstdea' --slot-name 'Production' --package .
            STATUS=$?
            if [ $STATUS -eq 0 ]; then
              echo "¡Despliegue exitoso!"
              exit 0
            else
              echo "Despliegue fallido (código $STATUS). Reintentando en 15 segundos..."
              sleep 15
            fi
          done
          echo "Despliegue fallido después de 3 intentos."
          exit 1