name: Build and deploy Node.js app to Azure Web App - travelstdea

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      
      - name: Zip artifact for deployment
        run: zip -r release.zip ./* -x "node_modules/*" "*.git*"
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      # Clear the .zip file after extraction
      - name: Remove zip file
        run: rm release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C289269F97494C6EA9E99490992A3961 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_96222BBB683243C8BD72D8DC5CA4144F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8BC739B6E0A145C28631C86FED07216A }}
      
      # Add step to handle existing deployments and clean up to prevent 409 conflicts
      - name: Check and clean previous deployments
        run: |
          # Install Azure CLI extensions for webapp
          az extension add --name webapp
          
          # Stop the web app to release locks
          echo "Stopping web app to release any locks..."
          az webapp stop --name travelstdea --resource-group $(az webapp show --name travelstdea --query resourceGroup --output tsv)
          
          # List all deployment IDs 
          echo "Listing current deployments..."
          DEPLOYMENTS=$(az webapp deployment list --name travelstdea --resource-group $(az webapp show --name travelstdea --query resourceGroup --output tsv) --query [].id --output tsv)
          
          # Delete each deployment except the latest one
          if [ ! -z "$DEPLOYMENTS" ]; then
            echo "Removing previous deployments..."
            COUNT=0
            for DEPLOYMENT_ID in $DEPLOYMENTS; do
              # Keep the latest deployment (usually the last in the list)
              if [ $COUNT -lt $(($(echo "$DEPLOYMENTS" | wc -l) - 1)) ]; then
                echo "Deleting deployment: $DEPLOYMENT_ID"
                az webapp deployment delete --name travelstdea --resource-group $(az webapp show --name travelstdea --query resourceGroup --output tsv) --id $DEPLOYMENT_ID
              fi
              COUNT=$((COUNT + 1))
            done
          else
            echo "No existing deployments found."
          fi
          
          # Start the web app again
          echo "Starting web app..."
          az webapp start --name travelstdea --resource-group $(az webapp show --name travelstdea --query resourceGroup --output tsv)
          
          # Small delay to ensure all operations complete
          sleep 10
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'travelstdea'
          slot-name: 'Production'
          package: .
          clean: true